[pytest]

addopts = -s -v

testpaths = Tests

markers = 
    sanity: marks a sanity test (basic quick check)
    regression: marks a regression test (full end to end validation)
    datadriven: marks a datadriven test
    end_to_end: marks end to end test